// "use client";
import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import GNB from "@/layouts/gnb";
import { css } from "../../styled-system/css/css";
import { ThemeProvider } from "styled-components";
import { theme } from "./../theme";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles } from "@/GlobalStyles";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "밍블로그 ",
  description: "Generated by create next app",
};

const bgStyle =
  "bg-blue-800 p-10 max-w-screen-xl min-w-[320px] text-white mx-auto";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={bgStyle}>
        <StyledComponentsRegistry>
          {/* <ThemeProvider theme={theme}> */}
          <GlobalStyles />
          <GNB />
          {children}
          {/* </ThemeProvider>s */}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
